name: MERGE

on:
  pull_request:
    branches:
    - main
    types: [closed]

concurrency:
  group: merge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy AWS CDK Stack
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Current User
        run: echo $GITHUB_ACTOR

      - name: Check Out Code
        uses: actions/checkout@v3.0.2

      - name: Setup Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Build Stack
        run: npm run build

      - name: Lint Code
        run: npm run lint

      - name: Unit Tests
        run: npm run test

      - name: Deploy AWS CDK Stack
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'